Gemfile
Gemfile.lock
app/assets/javascripts/landing_page.coffee
app/assets/stylesheets/custom.scss
app/assets/stylesheets/landing_page.scss
app/controllers/landing_page_controller.rb
app/helpers/landing_page_helper.rb
app/views/landing_page/home.html.erb
app/views/layouts/_footer.html.erb
app/views/layouts/_header.html.erb
app/views/layouts/_rails_default.html.erb
app/views/layouts/_shim.html.erb
app/views/layouts/application.html.erb
config/routes.rb
test/controllers/landing_page_controller_test.rb

・Gemにbootstrapが動くように
・controller LandingPageの作成
・routesで’landing_page#home'をrootパスに設定
・layouts/application.html.erbを<head>、<header>、<footer>をパーシャル化
・stylesheets/custom.scssでビュー調整

Adding landing page

---

app/views/layouts/_header.html.erb
test/controllers/landing_page_controller_test.rb
test/integration/site_layout_test.rb
test/test_helper.rb

・landing pageのhomeリンクをrootパスにする
・Minitest Reportersの追加
・landing page controllerのテストとsite layoutの統合テスト

test the landing page

---

app/assets/stylesheets/custom.scss
app/controllers/users_controller.rb
app/helpers/users_helper.rb
app/views/layouts/application.html.erb
app/views/shared/_error_messages.html.erb
app/views/users/new.html.erb
app/views/users/show.html.erb
config/routes.rb
test/integration/users_signup_test.rb

投げられてなかったぽいですね・・・
これで投げられたと思います。

Finish signup

---

app/assets/javascripts/application.js
app/assets/javascripts/sessions.coffee
app/assets/stylesheets/sessions.scss
app/controllers/application_controller.rb
app/controllers/sessions_controller.rb
app/controllers/users_controller.rb
app/helpers/sessions_helper.rb
app/models/user.rb
app/views/layouts/_header.html.erb
app/views/sessions/new.html.erb
config/routes.rb
test/controllers/sessions_controller_test.rb
test/fixtures/users.yml
test/integration/site_layout_test.rb
test/integration/users_login_test.rb
test/integration/users_signup_test.rb
test/test_helper.rb

Implement basic login

---

app/assets/stylesheets/custom.scss
app/controllers/sessions_controller.rb
app/helpers/sessions_helper.rb
app/models/user.rb
app/views/sessions/new.html.erb
db/migrate/20180920063310_add_remember_digest_to_users.rb
db/schema.rb
test/helpers/sessions_helper_test.rb
test/integration/users_login_test.rb
test/models/user_test.rb
test/test_helper.rb

Implement advanced login

---

config/environments/development.rb
config/routes.rb
test/mailers/previews/user_mailer_preview.rb

add the mailer preview in develpment

---

app/assets/javascripts/relationships.coffee
app/assets/stylesheets/custom.scss
app/assets/stylesheets/relationships.scss
app/controllers/application_controller.rb
app/controllers/relationships_controller.rb
app/controllers/users_controller.rb
app/helpers/relationships_helper.rb
app/models/relationship.rb
app/models/user.rb
app/views/relationships/create.js.erb
app/views/relationships/destroy.js.erb
app/views/shared/_stats.html.erb
app/views/users/_follow.html.erb
app/views/users/_follow_form.html.erb
app/views/users/_unfollow.html.erb
app/views/users/show.html.erb
app/views/users/show_follow.html.erb
config/application.rb
config/routes.rb
db/migrate/20180921151123_create_relationships.rb
db/schema.rb
db/seeds.rb
test/controllers/relationships_controller_test.rb
test/controllers/users_controller_test.rb
test/fixtures/relationships.yml
test/integration/following_test.rb
test/models/relationship_test.rb
test/models/user_test.rb

Rails tutorial 14章
フォロー機能
feed以外

Add user following

---

app/assets/stylesheets/custom.scss
app/controllers/landing_page_controller.rb
app/controllers/users_controller.rb
app/models/user.rb
app/views/landing_page/home.html.erb
app/views/layouts/_header.html.erb
app/views/sessions/new.html.erb
app/views/users/index.html.erb
app/views/users/show.html.erb

Create user home, search user

---

config/environments/production.rb

Add the mailer function on heroku by sendgrid

---

app/views/users/_user.html.erb
test/integration/user_search_test_test.rb

ただユーザー検索のテストを書いただけです・・・。
コンフリクトに注意してください。

create user search test

---

app/controllers/long_term_goals_controller.rb
app/views/long_term_goals/index.html.erb

Disable users to create a goal on other user's page

---

test/controllers/long_term_goals_controller_test.rb
test/fixtures/long_term_goals.yml
test/integration/drag_and_drop_test.rb
test/models/long_term_goal_test.rb

長期目標のテスト
・コントローラー
・モデル
（ドラッグアンドドロップ機能テストはgemインストールなど時間かかるため、後回しにしました。）

Add long-term-goal tests for its controller and model

---

app/assets/javascripts/mid_term_goals.coffee
app/assets/javascripts/table_sort.js.coffee
app/assets/stylesheets/custom.scss
app/assets/stylesheets/mid_term_goals.scss
app/assets/stylesheets/table_sort.css.scss
app/controllers/long_term_goals_controller.rb
app/controllers/mid_term_goals_controller.rb
app/helpers/mid_term_goals_helper.rb
app/models/long_term_goal.rb
app/models/mid_term_goal.rb
app/views/long_term_goals/index.html.erb
app/views/mid_term_goals/edit.html.erb
app/views/mid_term_goals/index.html.erb
app/views/mid_term_goals/new.html.erb
config/routes.rb
db/migrate/20180928051159_create_mid_term_goals.rb
db/schema.rb
db/seeds.rb
test/controllers/long_term_goals_controller_test.rb
test/controllers/mid_term_goals_controller_test.rb
test/fixtures/mid_term_goals.yml
test/models/mid_term_goal_test.rb

中期目標
new
create
index
edit
update
destroy

Add mid-term-goal function

---

app/assets/stylesheets/custom.scss
app/controllers/users_controller.rb
app/views/layouts/_header.html.erb
app/views/messages/_message_form.html.erb
app/views/users/show.html.erb
config/cable.yml
config/environments/production.rb

一応、参考記事の通りにやってみたのですが、これでもしherokuで出来なかったら教えてください・・・。
あと最低限のレイアウトを整えました。

finish user message

---

app/controllers/approaches_controller.rb
app/controllers/long_term_goals_controller.rb
app/controllers/mid_term_goals_controller.rb
app/controllers/short_term_goals_controller.rb
app/models/approach.rb
app/models/deadline.rb
app/models/long_term_goal.rb
app/models/mid_term_goal.rb
app/models/short_term_goal.rb
app/views/approaches/edit.html.erb
app/views/approaches/new.html.erb
app/views/long_term_goals/_l_goal.html.erb
app/views/long_term_goals/new.html.erb
app/views/modals/_approach_edit.html.erb
app/views/modals/_approach_new.html.erb
app/views/modals/_l_goal_edit.html.erb
app/views/modals/_l_goal_new.html.erb
app/views/modals/_m_goal_edit.html.erb
app/views/modals/_m_goal_new.html.erb
app/views/modals/_s_goal_edit.html.erb
app/views/modals/_s_goal_new.html.erb
db/migrate/20181003012925_create_deadlines.rb
db/schema.rb
test/models/deadline_test.rb

Add deadline function to the goals and the approach

---

app/controllers/likes_controller.rb
app/views/likes/_a_like.html.erb
app/views/likes/_l_like.html.erb
app/views/likes/_m_like.html.erb
app/views/likes/_s_like.html.erb
app/views/likes/index.html.erb
config/routes.rb

Add a like-user list page

---

Gemfile.lock
app/assets/javascripts/channels/xroom.coffee
app/assets/javascripts/xrooms.coffee
app/assets/stylesheets/xrooms.scss
app/channels/application_cable/connection.rb
app/channels/xroom_channel.rb
app/controllers/xrooms_controller.rb
app/helpers/xrooms_helper.rb
app/jobs/xmessage_broadcast_job.rb
app/models/user.rb
app/models/xmessage.rb
app/models/xroom.rb
app/views/layouts/_header.html.erb
app/views/messages/_message_form.html.erb
app/views/users/show.html.erb
app/views/xmessages/_xmessage.html.erb
app/views/xrooms/index.html.erb
app/views/xrooms/new.html.erb
app/views/xrooms/show.html.erb
config/routes.rb
db/migrate/20181011063109_create_xmessages.rb
db/migrate/20181011071423_create_xrooms.rb
db/migrate/20181011071527_add_columns_to_xmessages.rb
db/schema.rb
test/controllers/xrooms_controller_test.rb
test/fixtures/xmessages.yml
test/fixtures/xrooms.yml
test/jobs/xmessage_broadcast_job_test.rb
test/models/xmessage_test.rb
test/models/xroom_test.rb

Add x-room function and fix message form's location

---

app/assets/javascripts/channels/xroom.coffee
app/assets/stylesheets/custom.scss
app/controllers/xrooms_controller.rb
app/views/xmessages/_xmessage.html.erb
app/views/xrooms/index.html.erb
app/views/xrooms/new.html.erb
app/views/xrooms/show.html.erb
db/migrate/20181012033958_add_column_to_xroom.rb
db/schema.rb

Add a basic layout to the xmessage

---

app/assets/stylesheets/custom.scss
app/controllers/xrooms_controller.rb
app/views/xmessages/_xmessage.html.erb
app/views/xrooms/_xroom.html.erb
app/views/xrooms/index.html.erb
app/views/xrooms/show.html.erb
config/routes.rb

Add basic layout to the xroom list page

---

app/views/long_term_goals/_l_goal.html.erb
app/views/long_term_goals/_m_goal.html.erb
app/views/long_term_goals/index.html.erb

Ajax起点となるclass+idの追加
インスタンス変数をローカルにする
Ajax起点となるパーシャルの追加

Fix l-goal function

---

app/assets/stylesheets/custom.scss

Make break-word in xmessage

---

app/assets/javascripts/channels/chat.coffee
app/assets/javascripts/channels/xroom.coffee
app/assets/stylesheets/custom.scss
app/controllers/users_controller.rb
app/views/messages/_message.html.erb
app/views/messages/_message_form.html.erb
app/views/users/show.html.erb
app/views/xmessages/_xmessage.html.erb
app/views/xrooms/show.html.erb

基礎レイアウト＝＞message
改行テキスト＝＞message + xmessage

Add basic layout to message

---

app/assets/javascripts/channels/xroom.coffee
app/channels/xroom_channel.rb
app/controllers/xrooms_controller.rb
app/jobs/xmessage_broadcast_job.rb
app/jobs/xuser_broadcast_job.rb
app/models/subscription.rb
app/models/xroom.rb
app/views/xrooms/_xroom.html.erb
app/views/xrooms/_xroom_user.html.erb
app/views/xrooms/show.html.erb
db/migrate/20181015054050_create_subscriptions.rb
db/schema.rb
test/fixtures/subscriptions.yml
test/jobs/xuser_broadcast_job_test.rb
test/models/subscription_test.rb

Update xroom user lists at live time

---

app/assets/javascripts/channels/xroom.coffee
app/jobs/xuser_broadcast_job.rb
app/views/layouts/_header.html.erb
app/views/xrooms/_xroom.html.erb
app/views/xrooms/_xroom_user.html.erb
app/views/xrooms/show.html.erb

fix the live-user lists

---

app/assets/javascripts/channels/xroom.coffee
app/models/subscription.rb

リアルタイムユーザーリストのデバッグ再トライ
perform_later -> perform_now

Fix the live user list again

---

app/assets/javascripts/channels/xroom.coffee
app/assets/stylesheets/custom.scss
app/controllers/application_controller.rb
app/controllers/xrooms_controller.rb
app/models/xroom.rb
app/views/layouts/application.html.erb
app/views/xrooms/index.html.erb
config/routes.rb

Add xroom search function

---

app/assets/javascripts/channels/notification.coffee
app/assets/stylesheets/custom.scss
app/assets/stylesheets/notices.scss
app/channels/notification_channel.rb
app/controllers/comments_controller.rb
app/controllers/likes_controller.rb
app/controllers/notices_controller.rb
app/helpers/notices_helper.rb
app/jobs/notice_broadcast_job.rb
app/models/message.rb
app/models/notice.rb
app/models/user.rb
app/views/layouts/_header.html.erb
app/views/notices/_notice.html.erb
app/views/notices/_notice_form.html.erb
app/views/notices/index.html.erb
app/views/short_term_goals/_approach.html.erb
config/routes.rb
db/migrate/20181020043219_create_notices.rb
db/migrate/20181021102033_rename_user_id_column_to_notices.rb
db/migrate/20181023025100_change_notice_column.rb
db/migrate/20181023090744_change_notice_column_2.rb
db/schema.rb
test/controllers/notices_controller_test.rb
test/fixtures/notices.yml
test/jobs/notice_broadcast_job_test.rb
test/models/notice_test.rb

create notice for goal, approach, like, comment and message

---

db/migrate/20181021102033_rename_user_id_column_to_notices.rb

fix notice migration

---

app/views/landing_page/_xroom.html.erb
db/seeds.rb

・xroomレイアウトをホームページなどのパーシャルに適用
・seedデータの作成

Apply xroom-layout to the other partials

---

app/assets/stylesheets/custom.scss
app/views/comment_replies/_comment_reply_form.html.erb
app/views/comment_replies/index.html.erb
app/views/comments/_comment_form.html.erb
app/views/comments/index.html.erb
app/views/long_term_goals/_l_goal.html.erb
app/views/mid_term_goals/index.html.erb
app/views/short_term_goals/index.html.erb

edit comment layout

---

app/assets/stylesheets/custom.scss
app/views/approaches/_save.js.erb
app/views/landing_page/_approach.html.erb
app/views/landing_page/_calendar.html.erb
app/views/landing_page/_goal_overview.html.erb
app/views/landing_page/_l_goal.html.erb
app/views/landing_page/_m_goal.html.erb
app/views/landing_page/_s_goal.html.erb
app/views/landing_page/home.html.erb
app/views/long_term_goals/_save.js.erb
app/views/mid_term_goals/_save.js.erb
app/views/search/_approach.html.erb
app/views/search/_l_goal.html.erb
app/views/search/_m_goal.html.erb
app/views/search/_s_goal.html.erb
app/views/short_term_goals/_save.js.erb

Add the goal overview diagram

---

app/assets/stylesheets/custom.scss

Fix the goal overview

---

app/assets/stylesheets/custom.scss
app/views/landing_page/_goal_overview.html.erb

Add border to the overview
